// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class documentmodelnewpropDokumenttype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(documentmodelnewpropDokumenttype));
        
        string IMigrationMetadata.Id
        {
            get { return "201708182207004_document model new prop Dokumenttype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
