// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedICollectionDocumentstocoursemoduleactivityperson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedICollectionDocumentstocoursemoduleactivityperson));
        
        string IMigrationMetadata.Id
        {
            get { return "201708170635007_Added ICollection Documents to course, module, activity, person,"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
